# Generated by Django 5.1.3 on 2024-12-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='solde',
            field=models.IntegerField(default=5000.0, verbose_name='Solde disponible dans le compte'),
        ),
    ]
