# Generated by Django 5.1.3 on 2024-11-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userregistrationmodel_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
