# Generated by Django 5.0.9 on 2024-12-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='date_of_creation',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='date_of_update',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='date_of_creation',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='date_of_update',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_creation',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_update',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
