# Generated by Django 5.1.3 on 2024-12-03 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('date_of_creation', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('date_of_update', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True)),
                ('result_of_the_operation', models.CharField(max_length=50)),
                ('status_of_the_operation', models.BooleanField(default=False)),
                ('duration_of_the_operation', models.DurationField(default=0)),
                ('description_of_the_operation', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_creation'],
            },
        ),
    ]
