# Generated by Django 5.0.9 on 2024-11-13 07:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('date_of_creation', models.DateTimeField(auto_created=True)),
                ('date_of_update', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True)),
                ('amount', models.IntegerField(verbose_name='montant')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_creation'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('date_of_creation', models.DateTimeField(auto_created=True)),
                ('date_of_update', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True)),
                ('message', models.TextField(max_length=300)),
                ('as_read', models.BooleanField(default=False)),
                ('transaction_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'ordering': ['-transaction_id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('date_of_creation', models.DateTimeField(auto_created=True)),
                ('date_of_update', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True)),
                ('sender_account_id', models.EmailField(max_length=100, verbose_name='sender')),
                ('receiver_account_id', models.CharField(max_length=100, verbose_name='receiver')),
                ('transaction_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'ordering': ['-sender_account_id'],
            },
        ),
    ]
