# Generated by Django 5.1.3 on 2024-12-03 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('date_of_creation', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('date_of_update', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True)),
                ('base_currency', models.CharField(default='XAF', max_length=3)),
                ('target_currency', models.CharField(default='RUB', max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
            options={
                'ordering': ['-base_currency'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('date_of_creation', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('date_of_update', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True)),
                ('amount', models.IntegerField(verbose_name='montant')),
                ('devise', models.CharField(blank=True, choices=[('EURO', 'euro'), ('FCFA', 'fcfa'), ('DOLLARS', 'dollars'), ('ROUBLE', 'RUB')], max_length=255, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'en_cours'), ('TERMINE', 'termine'), ('ECHOUE', 'echoue')], default='en_cours', max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type_transaction', models.CharField(blank=True, choices=[('DEPOT', 'depot'), ('RETRAIT', 'retrait')], max_length=255, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-amount'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('date_of_creation', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('date_of_update', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True)),
                ('message', models.TextField(max_length=300)),
                ('as_read', models.BooleanField(default=False)),
                ('transaction_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'ordering': ['-transaction_id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('date_of_creation', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('date_of_update', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('transaction_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sender'],
            },
        ),
    ]
