# Generated by Django 5.0.9 on 2024-11-20 04:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('date_of_creation', models.DateTimeField(auto_created=True)),
                ('date_of_update', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True)),
                ('base_currency', models.CharField(default='XAF', max_length=3)),
                ('target_currency', models.CharField(default='RUB', max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
            options={
                'ordering': ['-base_currency'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='devise',
            field=models.CharField(blank=True, choices=[('EURO', 'euro'), ('FCFA', 'fcfa'), ('DOLLARS', 'dollars'), ('ROUBLE', 'RUB')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'en_cours'), ('TERMINE', 'termine'), ('ECHOUE', 'echoue')], default='En_Cours', max_length=255),
        ),
    ]
