# Generated by Django 5.0.9 on 2024-11-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_devise_transaction_devise_transaction_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(blank=True, choices=[('DEPOT', 'depot'), ('RETRAIT', 'retrait')], max_length=255, null=True),
        ),
    ]
