# Generated by Django 5.1.3 on 2024-11-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transactionhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'en_cours'), ('TERMINE', 'termine'), ('ECHOUE', 'echoue')], default='en_cours', max_length=255),
        ),
    ]
